import Footer from '@/components/footer';
import './globals.css'
import type { Metadata } from 'next'
import localFont from "next/font/local";
import Navbar from '@/components/navbar';

const BRFrima = localFont({
  src: [
    {
      path: '../fonts/BRFirma-font/BRFirma-Light.woff2',
      weight: '100',
      style: 'normal'
    },
    {
      path: '../fonts/BRFirma-font/BRFirma-Regular.woff2',
      weight: '200',
      style: 'normal'
    },
    {
      path: '../fonts/BRFirma-font/BRFirma-Medium.woff2',
      weight: '300',
      style: 'normal'
    },
    {
      path: '../fonts/BRFirma-font/BRFirma-SemiBold.woff2',
      weight: '400',
      style: 'normal'
    },
    {
      path: '../fonts/BRFirma-font/BRFirma-Bold.woff2',
      weight: '500',
      style: 'normal'
    },
  ]
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={BRFrima.className}>
      <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
